---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  labels:
    app: cluster-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-autoscaler
  template:
    metadata:
      namespace: kube-system
      labels:
        app: cluster-autoscaler
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8085'
    spec:
      serviceAccountName: cluster-autoscaler
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/master: ""
      priorityClassName: system-cluster-critical
      containers:
        - name: cluster-autoscaler
          image: brightbox/cluster-autoscaler-brightbox:dev
          imagePullPolicy: Always
          command:
            - ./cluster-autoscaler
          args:
            - --cluster-name=kubernetes.cluster.local
            - --skip-nodes-with-local-storage=false
            - --cloud-provider=brightbox
            - --v=4
            - --alsologtostderr
          envFrom:
          - secretRef:
              name: brightbox-credentials
          livenessProbe:
            httpGet:
              path: /health-check
              port: 8085
          readinessProbe:
            httpGet:
              path: /health-check
              port: 8085
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 300Mi
